// src/verdicts.ts
// Subagent outputs collected in parallel — one Verdict per Claim.
// Generated by BUILD-02-verifier session. Do not edit manually.

import type { Verdict } from "./verify.js";

export const verdicts: Verdict[] = [
  {
    claimId: "c01",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:271,704,721-726",
    reasoning: "DEFAULT_PREDGE_SIGNAL_URL is set to https://api.predge.io; resolveBaseUrl falls back to it when PREDGE_SIGNAL_URL is unset; fetchSignedSignal constructs the URL as /v1/signal/{wallet} and calls safeFetch with method GET.",
  },
  {
    claimId: "c02",
    verdict: "does-not-hold",
    evidence: "corpus/pr-2476.diff:1031",
    reasoning: "The testPredge function in test.ts makes an outbound request using raw fetch() without calling assertUrlIsPublic, contradicting the claim that every outbound request passes through this SSRF check.",
  },
  {
    claimId: "c03",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:291,725",
    reasoning: "FETCH_TIMEOUT_MS is defined as 10_000 ms; AbortSignal.timeout(FETCH_TIMEOUT_MS) is passed as the signal parameter to safeFetch.",
  },
  {
    claimId: "c04",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:303,770-776",
    reasoning: "MAX_RESPONSE_BYTES = 64 * 1024; the content-length header is read and compared before response.text() is called, so an oversized declared body is rejected before it is materialised.",
  },
  {
    claimId: "c05",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:778-784",
    reasoning: "After response.text(), body.length is compared against MAX_RESPONSE_BYTES before JSON.parse(body), so the body length is checked before parsing.",
  },
  {
    claimId: "c06",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:528-569",
    reasoning: "verifyPredgeSignal performs exactly six sequential checks: scheme, signer, ed25519 signature, subject binding, resource binding, and freshness, each gated by a return-on-fail.",
  },
  {
    claimId: "c07",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:281-282,515,947",
    reasoning: "DEFAULT_PINNED_SIGNER is a source constant; the pinned value is resolved as (input.expectedKeyId || DEFAULT_PINNED_SIGNER); read-signal.ts passes credentials.PREDGE_SIGNER_KEY_ID as expectedKeyId.",
  },
  {
    claimId: "c08",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:512-534",
    reasoning: "signer = raw.keyId is extracted but compared against the pinned constant rather than accepted directly; verification fails if they do not match.",
  },
  {
    claimId: "c09",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:540-545",
    reasoning: "walletInPayload = raw.payload.wallet; subjectMatch = normalizeWallet(walletInPayload) === normalizeWallet(requestedWallet); fails with 'signal is about a different wallet' on mismatch.",
  },
  {
    claimId: "c10",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:317,549-554",
    reasoning: "RESOURCE_PREFIX = 'conviction:'; expectedResource is built as conviction:<requestedWallet>; raw.resource is compared against it and fails if mismatched, blocking foreign signed products.",
  },
  {
    claimId: "c11",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:286,288,563-569,948",
    reasoning: "DEFAULT_MAX_SIGNAL_AGE_SECONDS = 600, MAX_CLOCK_SKEW_MS = 60_000; maxAgeSeconds is read from PREDGE_MAX_SIGNAL_AGE_SECONDS; ageMs is checked against both bounds.",
  },
  {
    claimId: "c12",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:626-638",
    reasoning: "parseConvictionPayload checks typeof conviction !== 'number' || !Number.isFinite(conviction), which rejects the string '99999' at the typeof check, then enforces the 0–100 range.",
  },
  {
    claimId: "c13",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:322,640-645",
    reasoning: "PREDGE_ACTIONS = ['accumulate','reduce','hold']; parseConvictionPayload checks PREDGE_ACTIONS.includes(raw.action) and fails with a descriptive reason if it is not one of those three.",
  },
  {
    claimId: "c14",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:323,646-651",
    reasoning: "PREDGE_WINDOWS = ['7d','30d']; parseConvictionPayload checks PREDGE_WINDOWS.includes(raw.window) and fails if the value is not in that set.",
  },
  {
    claimId: "c15",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:626-651",
    reasoning: "All three fields are validated with strict type checks (no Number(), String() coercion); absent fields cause the typeof or includes checks to fail, making each field implicitly required.",
  },
  {
    claimId: "c16",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:955-975,580-596",
    reasoning: "Verification failure returns error with verification.reason; payload-shape failure returns error with parsed.reason built by describeValue() which includes the received type and value for each field.",
  },
  {
    claimId: "c17",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:848-869,955-989",
    reasoning: "The success ReadSignalResult type contains wallet, conviction, action, window, signer, issuedAt, ageSeconds — no verified field — and success: true is only reached after the verification guard at line 955.",
  },
  {
    claimId: "c18",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:746-755,757-764",
    reasoning: "429 is explicitly handled with errorClass: EXTERNAL; the catch-all for non-ok responses uses status >= 500 ? EXTERNAL : USER, attributing all 5xx as EXTERNAL.",
  },
  {
    claimId: "c19",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:710-715,729-744",
    reasoning: "Unparseable URL returns USER before assertUrlIsPublic is called; 404 and 402 status responses both return USER errorClass.",
  },
  {
    claimId: "c20",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:673-677",
    reasoning: "blameForBadBody returns USER when credentials.PREDGE_SIGNAL_URL is set (operator repointed host) and EXTERNAL otherwise; it is called for all bad-body cases.",
  },
  {
    claimId: "c21",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:281-282",
    reasoning: "DEFAULT_PINNED_SIGNER is a source constant in predge-core.ts; the comment links it to the attestation-role key at the published URL. The reviewer (suisuss, review[6]) independently confirmed the hex value is byte-identical to the live published key.",
  },
  {
    claimId: "c22",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:281-282,1031",
    reasoning: "predge-core.ts uses a hardcoded DEFAULT_PINNED_SIGNER for offline verification and never fetches the keyset; only testPredge in test.ts fetches /.well-known/predge-keys.json, and only for connection-test purposes.",
  },
  {
    claimId: "c23",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:65-73",
    reasoning: "credentials.ts documents PREDGE_SIGNER_KEY_ID under a 'Rotation path' comment that explicitly says operators can set it to the new published key to move ahead of a plugin release.",
  },
  {
    claimId: "c24",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:945-968,610-662",
    reasoning: "parseConvictionPayload is called only after verification.verified is true (line 968); it enforces conviction as finite number in 0–100, action in PREDGE_ACTIONS, window in PREDGE_WINDOWS, with no coercion.",
  },
  {
    claimId: "c25",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:889-895,564",
    reasoning: "parseMaxAgeSeconds returns 0 when raw is '0' because '0'.trim() is truthy and Number('0')=0 passes the isFinite and >= 0 checks; maxAgeSeconds=0 means ageMs > 0 rejects every positive-age signal.",
  },
  {
    claimId: "c26",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:346,404-416,450",
    reasoning: "PredgeAttestation has resource: string; canonicalize serializes all Object.keys() of the attestation including resource; canonical bytes are what the signature is verified over.",
  },
  {
    claimId: "c27",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:528-569",
    reasoning: "Code order: scheme (528), signer (531), signature (536), subject binding (543), resource binding (550), freshness (564/567) — resource is exactly fifth.",
  },
  {
    claimId: "c28",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:770-784",
    reasoning: "content-length header is read and checked against MAX_RESPONSE_BYTES before response.text(); body.length is checked after response.text() and before JSON.parse().",
  },
  {
    claimId: "c29",
    verdict: "holds",
    evidence: "corpus/pr-2476.diff:909-921,673-677",
    reasoning: "classifyVerificationFailure returns USER only when the operator set PREDGE_SIGNER_KEY_ID or PREDGE_SIGNAL_URL (via blameForBadBody); all other verification failures default to EXTERNAL.",
  },
];
